### PR TITLE
Allow chained custom prototypes

### PR DESCRIPTION
**Pull request by PsychoLlama**
> Previously proposed on develop branch

This PR will allow you to inherit from the gun constructor to create custom, scoped instances that carry through the chain. And it also includes readme changes (see commit messages) that were merged into the develop branch a while ago.

### CODE REVIEW

**Comment by amark** [comment]
Oooooh so this is what happened to this. I thought we had gotten this merged and then we noticed the other day it didn't have this anymore.

Think we can close this issue and re-open with a fix on the current master? Since it is like the one line.

ALTHOUGH IT IS THE WEEKEND, YOU SHOULD BE SKYDIVING OR WAKEBOARDING OR SOMETHING!

**Comment by PsychoLlama** [comment]
Pffft, weekends.

**Comment by amark** [comment]
We're too much nerd. :(

**Comment by amark** [comment]
did this do anything (?)

**Pull request merged**
