### PR TITLE
0.5 external websocket example fix

### PR DESCRIPTION
**Pull request by d3x0r**
fixes missing parenthesis, and badly named variables.

### CODE REVIEW

**Comment by amark** [comment]
@d3x0r I forget what you said happened to this? I'm gonna close since 0.5 is now on master. I'm sure you'll find some things that need to be fixed ;) feel free to PR then. Thanks for helping out so much!

**Comment by d3x0r** [comment]
should have pulled it :) 
there are obvious syntax errors in http-external-ws example... I hadn't tested that version yet and was just building it... 
This applies the missing parens.... I can rebase to head

**Comment by amark** [comment]
yeah and then I'll pull :) thanks!

**Comment by amark** [comment]
@d3x0r oh? I'm guessing this is ready? You didn't bump the pull with a comment so I didn't notice. I'm gonna pull and close it now.

**Comment by amark** [comment]
Oops. It was to an old branch which is now dead... harrummm, could you re-do this pull (only the changes you made) to master?

**Comment by d3x0r** [comment]
amark merged commit dea7720 into amark:0.5 6 hours ago

Pull request successfully merged and closed....

Nothing to be done; you've got it :)

**Pull request merged**
