### PR TITLE
Examples Cleanup & Quick deployments with Heroku, Docker etc.

### PR DESCRIPTION
**Pull request by hillct**
Developers new to Gun should be able to spin up a demo server for their dev team (Not just localhost) quickly and easily. This cleanup, improved documentation a inclusion of Docker build support will enhance Gun's visibility and accessibility to those looking to build realtime collaboration tools and applications across more than single-developer teams.

It should be noted that /examples/hello-world.js is broken  in the 0.5 branch and this patch does not address that brokenness.

### CODE REVIEW

**Comment by hillct** [comment]
The Travis-CI tests fail after updates to ONLY readme.md. That makes no sense except as a red herring. It turns out that upon closer inspection, it IS a red herring as it relates to this PR. The real issue is one of node and selenium-webdriver support. We need to tighten up the nod and Selenium driver versions allowed within package.json. Supported version details can be found here: https://www.npmjs.com/package/selenium-webdriver#node-support-policy

**Comment by amark** [comment]
@hillct this is absolutely brilliant. And you are correct, developers should be able to easily spin things up - and you've made this possible! That is awesome. Definitely pulling.

@hillct 0.5 tests are failing in general, this is not your fault. :) Once all 0.5 tests pass it'll become the new master/stable.

**Comment by Carringguns** [comment]
Thanks for the morale support. I didnt have the time to go fix em. And when I fillally hello world Travis CI assulted all,devices, mail, errors, in 1 and a half days. Very greatful for all the help and guidance.. im being creeped here. Facebk sure but her?. To funny. This is my extent on dev. Btw. I collect data and put ppl together.

**Comment by amark** [comment]
@Carringguns could you explain context? Did you need help with a gunDB hello world deployed to docker or something? I am not sure what you are needing. Let us know!

**Pull request merged**
