### PR TITLE
WS ws.path fix 

### PR DESCRIPTION
**Pull request by bmatusiak**
i found that i always run into issues with it processing the correct path.

so this should fix gun when using WebSockets with other ws protocols that attach to different paths (webpack , socket.io)

### CODE REVIEW

**Comment by bmatusiak** [comment]
cleaned up, ready to review @amark

**Comment by amark** [comment]
@bmatusiak cool, it seems like some `||` edge case? I don't quite understand but you seem to notice it fixes stuff & I appreciate that + trust you! You're awesome, an open source hero!!!!

**Comment by bmatusiak** [comment]
thanks!     ` || `  prevents overloading it i guess.  there was a edge case in the past from a comment i seen.. but i think what i did  was the original intent

**Comment by bmatusiak** [comment]
i think the edge was..   if you want to host gun.js but not use the websockets

**Pull request merged**
