### PR TITLE
Logo change: png to svg

### PR DESCRIPTION
**Pull request by PsychoLlama**
Improved definition by linking to an svg file instead of the png file. Sadly, that meant I couldn't statically size the image (it's scalable, after all), meaning I had to add an html attribute, meaning it's now written in html :disappointed:

### CODE REVIEW

**Comment by amark** [comment]
Woah what happened tot he Travis tests? They all exploded. Yay for SVG image though.

**Comment by PsychoLlama** [comment]
Travis has been failing since [build 399](https://travis-ci.org/amark/gun/builds/114449746) (mid-sentence commit)
Thankfully, our readme isn't an integral part of gun's test suite :grinning:

**Comment by amark** [comment]
oh this is on the develop branch. Gotcha okay that makes sense now. Yeah.

**Comment by PsychoLlama** [comment]
Oh dear! That would be another matter entirely. Yep, develop branch. Should I be putting it on another branch?

**Pull request merged**
