### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by amark** [comment]
@DanielRuf thanks! I wasn't aware of this (not very good at Travis) mind tossing a quick explanation of what it does out for me? I'll pull. 

What are you working in?

**Comment by amark** [comment]
* on not in. Lol

**Comment by DanielRuf** [comment]
Let me know if I can help here.

**Comment by amark** [comment]
@DanielRuf I was just looking for a quick explainer of what caching node_modules does/results in? (I'm guessing just faster Travis time)?

Like, if npm dependencies change, could this cause any problems on subsequent runs?

**Comment by DanielRuf** [comment]
> Like, if npm dependencies change, could this cause any problems on subsequent runs?

If there is a change Travis CI will create a new cache and add the changes.

See https://docs.travis-ci.com/user/caching/#How-does-caching-work%3F
> After the build we check for changes in the directory, create a new archive with those changes, and upload it to the remote storage.

**Comment by amark** [comment]
@DanielRuf thanks!!! :) :) :)

**Pull request merged**
