### PR TITLE
Update to play nice with React Native

### PR DESCRIPTION
**Pull request by sjones6**
A small update so RN likes the code :)

### CODE REVIEW

**Comment by amark** [comment]
@sjones6 this is great, and the only thing necessary to fix for RN???? The reason why Travis failed is because the line

https://github.com/amark/gun/pull/420/files#diff-c1f786f9ff0e2139627dff3e31ef54c9R1707

defeats the purpose of the `typeof` check, because referencing it before it is checked to exist or not will just cause it to crash if it doesn't exist (because JS is stupid).

My guess is that RN doesn't like overloading a "reserved variable" of `WebSocket` which is why you switched it to `WS`?

If so, I think it'll just be easier for me to make this change you've made (without the indentation that git is going crazier over) and actually just reject this PR, if that is okay with you? I'll double check with you on gitter.

**Comment by amark** [comment]
@sjones6 I have taken your changes in concept... and applied them to gun directly.

Please let me know if the new version of gun `v0.8.6` now works with React Native out of the box?

I checked out your https://github.com/sjones6/gun-react-native , but I do not know if/what any other changes were made other than `websocket`.

As such, I've made sure to **credit** you in the commit, but I'm rejecting/closing this PR.

Please make a new PR if the edits I made did not help / or if other changes need to be made to increase React Native support.

Thank you so much!!!!!!!

**Comment by sjones6** [comment]
@amark Yep, no problem. This didn't seem super elegant and was breaking the build. So that's lame.

I have looked at the Travis-CI setup, but I was also thinking that it would be good to run at least a basic test against RN with Travis. Not sure how to wire that up but that way you would at least get some confirmation that changes continue to work in RN.

**Comment by amark** [comment]
yeah, @sjones6 that is a great idea. I literally have no clue how Travis works... somebody set it up for me, and I'm magically happy it still runs/works. :P If you know somebody who can get it working, power to them! Some day I even hope to run the PANIC tests via Travis automatically, too! But yeah... I don't know how.

**Comment by sjones6** [comment]
Awesome sauce. Let me take a whack at it sometime. I've started setting up
Travis for all of my OS projects. I need to figure out RN <> Travis anyway.

Spencer

**Pull request closed without merging**
