### PR TITLE
YSON Escaped Backslash

### PR DESCRIPTION
**Pull request by Promaethius**
#1155 
The string getting passed into the unicode handler on https://github.com/amark/gun/blob/master/lib/yson.js#L33 ends up being `test\\",` I think this is a relic from https://github.com/amark/gun/blob/master/lib/yson.js#L27?

### CODE REVIEW

**Comment by amark** [comment]
@Promaethius thank you! So do tests pass if we just make it indexOf \\ rather than \\u?? Somebody smart with unicode/utf8 here? @jabis

**Comment by amark** [comment]
+ @Emad-salah maybe you can help with this?

**Comment by capitalistdog** [comment]
> * @Emad-salah maybe you can help with this?

checking a few things before a PR https://github.com/Emad-salah/gun/commit/2e4fea7518fa8866d258d5b8803b4cb4cc4f62ea

**Comment by amark** [comment]
Thanks everyone!

**Pull request merged**
