### PR TITLE
Angular demo

### PR DESCRIPTION
**Pull request by victornoel**
This a first shot an angular demo for gundb/feature-requests#18.

I've made two commits to see exactly what was gun-specific :)

It's not the best for now, in particular, accessing the objects using gun-edge (to get an rxjs `Observable`) gives an object with keys for the different paths, and so it is then needed to transform it in a array-like structure for it to be easily usable.

The object received via the Observable is like this:
```
{
  "_": {
    ">": {
      "SnP2p1oWETEzNvGorehQoGR9": 1492522724422.64,
      "rn6AACS4KfCddihZVgJ8pJRn": 1492522751260.65,
      "1WFiKpSSjOUzpTkoADIyn3EL": 1492523332021.265,
      "ZnNGO6w3L4Dxr3VFolUbHtQr": 1492523334677.69,
      "BU1Wak3Zc3MEN9N3dLIINqpk": 1492523335518.16,
      "Smxuc6beIghGpcWFrooM4bNK": 1492523336262.8,
      "j9eHsMA5wkklPslJxuhNefHP": 1492523344655.15,
      "0BeaiVN5ZXQt4bxyfcNbAzPV": 1492523351918.315
    },
    "#": "todos"
  },
  "SnP2p1oWETEzNvGorehQoGR9": "test",
  "rn6AACS4KfCddihZVgJ8pJRn": "test2",
  "1WFiKpSSjOUzpTkoADIyn3EL": "test5",
  "ZnNGO6w3L4Dxr3VFolUbHtQr": "lol",
  "BU1Wak3Zc3MEN9N3dLIINqpk": "lol",
  "Smxuc6beIghGpcWFrooM4bNK": "lol",
  "j9eHsMA5wkklPslJxuhNefHP": "haha",
  "0BeaiVN5ZXQt4bxyfcNbAzPV": "hoho"
}
```

Not sure how to improve this :)

### CODE REVIEW

**Comment by victornoel** [comment]
@amark (for gun) @kristianmandrup (for gun-edge) if you have any improvement idea, pleas share :)

**Comment by kristianmandrup** [comment]
Oh? What does this have to do with gun-edge. I gave up on Gun for now as suddenly nothing g worked for me in Node.js, could only get Gun working in browser. Docs and examples seem severely out of date...

**Comment by victornoel** [comment]
@kristianmandrup It's just that this demo mainly relies on gun-edge for its observable support and I was wondering if you had things to say about how I used it :)

**Comment by amark** [comment]
@victornoel holy wow cow, that looked very non-trivial to implement - I would have never figured out how to do this. Thank you! Sorry, I didn't know it required so much work. Very much appreciate it, people are gonna love having an Angular example though!!! Pulling.

@kristianmandrup gun suddenly stopped working? That seems odd, all tests are passing in both NodeJS+Browser, would you mind creating a GitHub issue with minimum viable code to reproduce, so we can fix whatever it is?

**Comment by victornoel** [comment]
@amark don't worry, it's not so non-trivial if you are familiar with angular :) the only bothering thing was the format of the data brought by gun which didn't fit well with the need for an array of object from angular html directives to loop over a set of data, but maybe some helpers exist to get an array of key/value or things like that from a gun node?

**Comment by kristianmandrup** [comment]
@amark I posted my problems various times on Gutter with no response. Could get hello work to work in node anymore... Some callback never gets called or sth? Just stalls when trying to get any element that was put. 

@victor, btw gun-edge is deprecated. Try future-gun instead ;) I split up gun-edge in smaller, more targeted modules.

**Comment by kristianmandrup** [comment]
@amark, I was trying to write a gun-json module to makenitneasier to marshal/unmarshal from Gun graph to JSON and back. You must be doing  the same over the wire? I gave up coz Gun was playing tricks with me, even as I npm linked to gun and debugged from within gun, it just swallowed everything... I had to processer.exit to stop it.
You have a working hello world for Node?

**Comment by kristianmandrup** [comment]
I wonder if errors are swallowed? The callback don't follow the node style, returning (err, result)

**Comment by victornoel** [comment]
@kristianmandrup future-gun or water-gun? For rx observables

**Comment by kristianmandrup** [comment]
@victor ah, I mean water-gun for streams

**Comment by victornoel** [comment]
@kristianmandrup ah but it's not on npmjs :)

**Comment by amark** [comment]
@victornoel just as a warning (if you haven't already figured this out) if you modify the data returned from you in gun, you probably need to copy it first (manually snapshot it) due to a current bug ( #322 ) that I'm in the middle of fixing. However if you are using @kristianmandrup 's stuff, I believe he already does this for you.

@kristianmandrup which hello world? The hello world in the examples directory? Shoot, you are right, that is ancient from like v0.2 or older and is currently broken. It needs to get deleted.

@kristianmandrup the chat room gets so busy at times it is easy for me to miss/forget about things. If you have found a bug, please please post them here to a new GitHub issue (with a minimum-viable sample of code that causes the error for me to debug), and then give me some time to prioritize and then fix it. Then you will know you aren't forgotten about :).

**Comment by kristianmandrup** [comment]
@amark thanks. Please update examples and docs to latest Gun and make sure hello world in node.js works. Then I might consider giving Gun another try. For now I'm taking a break from development. Burns me out... Have fun!

**Comment by kristianmandrup** [comment]
I've now published: chain-gun, future-gun and water-gun to npm

**Pull request merged**
