### PR TITLE
Allow  {pair.pub} to login with pass

### PR DESCRIPTION
**Pull request by bmatusiak**
Allow  {pair.pub} to login with pass

### CODE REVIEW

**Comment by bmatusiak** [comment]
with a fix for s3 (that affected Heroku)   https://github.com/amark/gun/issues/1232

**Comment by amark** [comment]
Oh nice! Epic. I didn't go line for line but it looked like roughly the right places for stuff to be done. (And since this is security stuff, NOTHING looked weird/fishy. Yay!)

Would you be willing to add a test for this? `test/sea/sea.js` copy one of the `it` functions (ones in the middle may be easier to reuse) then swap in sample login code/test. Then open `../mocha.html` in browser from file or run `mocha` command line in repo root.

thank you thank you thank you!

**Comment by bmatusiak** [comment]
```
      ✓ login users (560ms)
      ✓ logout, login via {pub} (399ms)
      ✓ save data (273ms)
```

**Comment by amark** [comment]
👏 👏 👏 🔥 🔥 🔥 @bmatusiak !!!

**Pull request merged**
