### PR TITLE
Spliced code, compilation step, Webpack, ES6

### PR DESCRIPTION
**Pull request by devel-pa**
Let's give it a try on Travis.

### CODE REVIEW

**Comment by amark** [comment]
Context: https://github.com/amark/gun/issues/218

Cool. Hmm, there has only been a minor edit in the last 13 days (I think) on the master branch which was this line: https://github.com/amark/gun/pull/215/commits/1760900d73c667ce00aaf9ce9383dd335eb26495 in the WebSocket adapter.

**Comment by devel-pa** [comment]
Indeed, already added on `b151`

**Comment by amark** [comment]
Oh, so why iz git complaining! :(

**Comment by devel-pa** [comment]
Probably doesn't like I deleted `gun.js`

**Comment by amark** [comment]
Lol. Ugh, most of the time when I delete stuff it is fine but I do recall having some problems occasionally with git while merging.

**Comment by devel-pa** [comment]
Solved, I hope

**Comment by amark** [comment]
NodeJS 5 passed. But on the others NPM seems to be skrewed up?

```

The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
```

**Comment by amark** [comment]
I am going to restart the whole Travis because it seems like the failure is NPM not your code or tests.

**Comment by devel-pa** [comment]
I was looking at that. Quite interesting as the version required is present into the available versions list.

**Comment by amark** [comment]
What on earth is NPM `EPEERINVALID`? I just checked NPM servers and they look up.

**Comment by devel-pa** [comment]
The older npm(s) installs `peerDependencies` and requires to match the versions. Theoretically should be no issue with what is in `package.json` but practically looks like it is. I'll remove the 2 packages for the moment as I don't have the full working code for them.

**Comment by devel-pa** [comment]
Probably never compatible with Node 0.6 and 0.8 because of NPM.

**Comment by amark** [comment]
@devel-pa they are getting pretty old. Compatibility (progressive enhancement) is pretty important to me (although most people in the industry don't care about it). I am potentially fine with "skipping" those 2 versions for now, temporarily. However, before "skipping" I would like to know/understand/why the failures are the failures - because they are NOT test failures, they are an NPM failure. Which too me seems odd, NPM should not have broken between a few days ago and now (regardless of your edits/commits). Could you explain why/what is going on with NPM so there isn't any black magic floating around? Thanks.

**Comment by devel-pa** [comment]
The NPM is is that `^` was not supported until a certain version.

One of the references found: https://github.com/npm/node-semver/issues/67

**Comment by amark** [comment]
Okay, so I noticed you switched `^` over to `~>` which should avoid this problem in 0.8, but NPM still complains?

**Comment by devel-pa** [comment]
Complains because there are packages that requires other packages with `^` on dependency tree

**Comment by amark** [comment]
Ooooh, hmmm. I'm surprised that those tools don't have better support, but anyways to get around that can I propose the following:

Devdependencies are just that... development. They aren't necessary for checking whether the code itself should pass tests. So a temporary solution would be we remove those devdependencies but add some comments in the configuration files or something that tells developers "If you are doing development you'll need to do an extra step of installing these tools."

That way the tests can run/pass for master (production) purposes, and any development quirks can be fixed with a simple separate `npm install` command on the side until we get everything sorted out.

**Comment by amark** [comment]
Also, I don't want to assume that you want to be involved in all this time consuming stuff - want to do a Skype/Hangouts in the next week or so and chat about `0.5` of gun?

**Comment by devel-pa** [comment]
I don't think that I will have enough time to be fully committed to Gun. 

In fact I wanted to learn how Gun works and if is a feasible replacement for PouchDB which has a good client side but a lot of work and research to do for server side (and I don't wanna use CouchDB)

It would be interesting to study first 0.5 branch, unfortunately I will chop it in small pieces like this one, I really don't like files bigger than 200 lines, not that I like more Webpack, but it's the most compatible with me. ES6 is for sugar syntax, pretty difficult to use .

A chat would be interesting, till then I'll try to fix this crazy carousel.

**Comment by amark** [comment]
@devel-pa of course, I never expect that from Open Source contributors, even one-off contributions make the whole community better! Just wanting to get to know you, your projects, your goals. What time zone are you in and when would be best for you? :)

You are going to love the `npm run unbuild` command in `0.5` then! Admittedly, I need to do more of that. It takes the main file and automatically splits it into a bunch of smaller pieces (not as tiny as they should be, but that is easy to improve upon later)! So that way it is easier for people to read the source code.

**Comment by amark** [comment]
Just some quick exciting (from my perspective, probably not to other people) other notes. The splitting apart is perfectly isomorphic! The split apart code runs/evaluates in NodeJS perfectly correctly, and the regular main file runs in NodeJS correctly as well as the browser, and the automatically split up code also works in the browser if you script tag them all together in the correct order. FINALLY, I hope (but haven't tested yet) that then people who love Webpack will be able to then webpack build/bundle the split up code into/however they want. I see this as being the best of all worlds and should make everybody happy - completely agnostic to all coding politics! ... well except spaces versus tabs. :/ :P

**Comment by devel-pa** [comment]
Looks like I failed again with Travis, I'm declaring myself beaten for this evening (I'm in Paris): GMT+0200 (Romance Daylight Time). 

I had a look over `0.5` and I start to be a little bit upset that I've wasted my time with current version :)))) Nah, it helped me learning the stuff and clarify my Pros and Cons.

I've seen you're interviews and screencasts and I must admit that I'm a bit afraid of our discussion as I'm opposite to your behavior: theory sucks and not so talkative ;), not mentioning an old, grumpy troll.

**Comment by amark** [comment]
Sorry, that is anti-climatic :(. Don't over-exhaust yourself though, there is no rush. :)

This is my fault, I do not have any notices/disclaimers that `0.5` is what is in active development and that master/stable is being deprecated. I'll try to add this into the readme. But I do think you are right that it is not a waste, additionally you'll have better insight/perspective/value to add since you've gone through it - and be able to critique where progress has been made, and where it might be missing.

Thanks for watching! That is an honor. But don't worry, I don't bite! ;) And while I do love theory, I'll try my best to shut up, lol. Look, I don't even know you but I can immediately tell that how you've interacted is a sign of maturity. Old and grumpy maybe, but I bet for good reasons that are based on a lot of good experience. So I would still love to chat (I know I don't seem like an introvert, but I really am [at least that is what the stupid Myers-Briggs personality test says], so I understand).

**Comment by amark** [comment]
Been a while, I'm sure you are busy with work and stuff. Just wanted to check back in. Hope you are doing well!

**Comment by devel-pa** [comment]
@amark Hi, a little bit ill and taking time to set my home server :) I hope you're well.

Mu conclusion with this build is: impossible. And the only reason is that test framework `mocha` v3 is incompatible. So the only way to be compatible is `mocha` downgrade.

**Comment by devel-pa** [comment]
Probably you should have a good business reason that you still want to keep compatibility with those versions as long as node v6 will become LTS in 2 weeks. I don't really have any, so a minimum compatibility with node v4 and modern browser is the horizon I'm seeing for any app ready in the next half of year.

**Comment by devel-pa** [comment]
A quite busy week, Thursday and Friday are my only evenings that I still own, if you still wanna chat.

**Comment by amark** [comment]
@devel-pa Friday sounds great. 7pm Paris time is 11am my time. That sound good? My skype is 'mark.nadal' :)!

**Comment by devel-pa** [comment]
Sounds great.

**Comment by devel-pa** [comment]
Ohh, my MF god, not as I wanted, but passes.

**Comment by amark** [comment]
@devel-pa what is your Skype?

**Comment by devel-pa** [comment]
imasia
I've made a request

**Comment by amark** [comment]
0.5 has been merged into master with the `npm run unbuild` command that you helped build as a better solution than this PR. As a result, I am gonna close. Thanks for helping out with 0.5 !

**Comment by Silur** [comment]
then why can't I find it in current master, has it been removed since?

**Comment by amark** [comment]
@Silur sorry for the delayed response. Been in SF almost every week the last few weeks.

We chose to go with an `unbuild` process to splice the code, you can see `src/` vs `gun.js`. However we chose not to go with Webpack and ES6 as it killed my productivity (although I encourage others to use it if it makes them more productive).

**Pull request closed without merging**
