### PR TITLE
infinite scrolling example

### PR DESCRIPTION
**Pull request by mmalmi**
Blazing fast infinite scroll

- [x] InfiniteScrollWindow - reusable class for scrolling through gun nodes
- [x] Down from top infinite scroll
- [x] Up from bottom infinite scroll
- [ ] Fix issue: if scrolling quickly, you can scroll past top and bottom sentinels without observer noticing
- [x] Write panic test
- [ ] ~~Optimize InfiniteScrollWindow to better handle large gun nodes~~

Preview: https://gun-infinite-scroll.netlify.app/infinite-scroll/

### CODE REVIEW

**Comment by amark** [comment]
Should I merge now? :) Or wait for the other items to be checked?

Super thanks for the preview too. This is faaaaantaaaaastic, so excited to test it against manhattan and see if manhattan performs better on it.

**Comment by mmalmi** [comment]
You can merge!

Slowness while scrolling _down_ is because `{'-': true}` doesn't actually reverse the ordering.

**Comment by mmalmi** [comment]
Just added a simple panic test that scrolls through 1500 entries.

**Comment by amark** [comment]
Waaaaaaahoooooooooo!!!!!

**Pull request merged**
