### PR TITLE
package.json: dependencies use ~>; node & iojs engines use >= ;  adds repository field

### PR DESCRIPTION
**Pull request by metasean**
Changed all packaged dependencies to greater than or equal to (>=) instead of approximately equivalent to version greater than (~>) which was functionally just approximately equivalent to version (~) and wouldn't use more recent packages.  For more information refer to https://docs.npmjs.com/files/package.json#dependencies

### CODE REVIEW

**Comment by amark** [comment]
Hmm, Mocha's devDependency seemed to be causing a problem. I honestly don't understand what is going on though. Sometimes NPM does weird things. Now what?

**Comment by coolaj86** [comment]
`>=` Is a bad idea. It will allow packages with API breaking changes to be installed. Stick to the style of `~>` or `1.x` (less conventional, but definitely more readable).

**Comment by metasean** [comment]
RoboCI for TravisCI- http://phptest.club/t/roboci-run-travisci-builds-locally/170

**Comment by amark** [comment]
Yay all is well! Could you add git rm ".idea/workspace.xml" from the pull request?

And then @coolaj86 I'll probably pull, but you think ">=" is bad? Could you explain the differences between "~>" (Sean suggested "~>" doesn't work, because "~" trumps ">"), like what magically makes one cause breaking API changes and the other not?

I don't understand how NPM's ~ > * commands work, and semantic version just adds to my confusion... Travis has been saying things like '0.1' is more recent than '0.11' and things like that.

**Comment by metasean** [comment]
Corrected in af86b7ccef1c972f0d210f12c80a54d2d21ecad9

**Comment by amark** [comment]
Fixed in master at c12de322a40ae7b4e527d6c9c6677f32ddd2482c . Closing :).

**Pull request closed without merging**
