### PR TITLE
Something like this should fix #422

### LINKED ISSUE #422: Gun doesn't work in node-to-node setup
node 6.11.1
gun 0.8.5

I get no response from Gun server.

Client code, [this](https://github.com/amark/gun/wiki/graphs) example:
```
const Gun = require('gun');

const gun = Gun('http://localhost:8080/gun');

const alice = gun.get('person/alice').put({name: 'alice', age: 22});
const bob = gun.get('person/bob').put({name: 'bob', age: 24});
const carl = gun.get('person/carl').put({name: 'carl', age: 16});
const dave = gun.get('person/dave').put({name: 'dave', age: 42});

alice.on(function(node){
  console.log('Subscribed to Alice!', node);
});

console.log('==============', 'get Bob data');
gun.get('person/bob').val(function(node){
  console.log('Bob!', node);
});

const people = gun.get('people');
people.set(alice);
people.set(bob);
people.set(carl);
people.set(dave);

console.log('==============', 'get people data');
people.map().val(function (person) {
  console.log('The person is', person);
});

const company = gun.get('startup/hype').put({
  name: "hype",
  profitable: false,
  address: {
    street: "123 Hipster Lane",
    city: "San Francisco",
    state: "CA",
    country: "USA"
  }
});

console.log('==============');
company.val(function(startup){
  console.log("The startup:", startup);
});
company.get('address').get('city').val(function(value, key){
  console.log("What is the city?", value);
});
gun.get('startup/hype').put({ // or you could do `company.put({` instead.
  funded: true,
  address: {
    street: "999 Expensive Boulevard"
  }
});

const employees = company.get('employees');
employees.set(dave);
employees.set(alice);
employees.set(bob);

alice.get('spouse').put(bob);
bob.get('spouse').put(alice);

alice.get('spouse').get('employer').put(company);
alice.get('employer').put(company);

dave.get('kids').set(carl);
carl.get('dad').put(dave);

carl.get('friends').set(alice);
carl.get('friends').set(bob);

console.log('================', 'read related data');
gun.get('person/alice').get('spouse').get('employer').get('employees').map().get('name').val(function(data, key){
  console.log("The employee's", key, data);
});
```

Server code:
```
const Hapi  = require('hapi')
const Inert = require('inert')
const Gun   = require('gun')

const server = new Hapi.Server
server.connection({ port: 8080 })
server.connections.forEach(c => Gun({ web: c.listener, file: 'data.json' }))

server.register(Inert, () => {});

server.route({
  method: 'GET',
  path: '/gun.js',
  handler: (request, reply) => reply.file('./gun.js', { confine: false })
})

server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: __dirname,
      redirectToSlash: true,
      index: true
    }
  }
})

server.start()
```

### PR DESCRIPTION
**Pull request by d3x0r**

### CODE REVIEW

**Comment by sergibondarenko** [comment]
I tried your patch in my scripts https://github.com/amark/gun/issues/422, it didn't work

**Comment by sergibondarenko** [comment]
I still don't receive any data. I did the following.

1. Downloaded your repo and checked into your patch.
```
trex@beast-cave:~/dev/learn/gun/gun$ git remote -v
origin  git@github.com:d3x0r/gun.git (fetch)
origin  git@github.com:d3x0r/gun.git (push)
trex@beast-cave:~/dev/learn/gun/gun$ git branch
  master
* patch-17
trex@beast-cave:~/dev/learn/gun/gun$ git pull
Already up-to-date.
```

2. Have the [graph tutorial](https://github.com/amark/gun/wiki/graphs) data available, full data is [here](https://gist.github.com/sergibondarenko/f59386ef66caf16ae351f8f9fdc8da9e).
```
trex@beast-cave:~/dev/learn/gun/server$ head -c 200 data.json
{"person/alice":{"_":{"#":"person/alice",">":{"name":1505750977100,"age":1505750977100,"spouse":1505750977133.001,"employer":1505750977141.002}},"name":"alice","age":22,"spouse":{"#":"person/bob"},"em...
```

3. Run server.
Run `node hapi.js`
```
trex@beast-cave:~/dev/learn/gun/server$ cat hapi.js
const Hapi  = require('hapi')
const Inert = require('inert')
const Gun   = require('../gun/')

const server = new Hapi.Server
server.connection({ port: 8080 })
server.connections.forEach(c => Gun({ web: c.listener, file: 'data.json' }))

server.register(Inert, () => {});

server.route({
  method: 'GET',
  path: '/gun.js',
  handler: (request, reply) => reply.file('./gun.js', { confine: false })
})

server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: __dirname,
      redirectToSlash: true,
      index: true
    }
  }
})

server.start()
```

4. Query data
```
const Gun = require('gun');
const gun = Gun({ peers:['http://localhost:8080/gun'] });
gun.get('person/alice').get('spouse').get('employer').get('employees').map().get('name').val(function(data, key){
  console.log("The employee's", key, data);
});
```

No results in the console output.

**Comment by sergibondarenko** [comment]
I tested this patch with my example and it worked.

**Comment by amark** [comment]
@d3x0r you are a life saver! I'm still confused why this works??? (`if(!x) return` versus `if(x) do`?) Pulling.

**Comment by d3x0r** [comment]
@amark :) because the if( x) do only does the top open/attach server part... the remaining ctx.on()s were being skipped with the return at the top... so this allows the on( out ) to be regsitered and trigger opening the peers as required.

**Pull request merged**
