### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eschapp**
Just a quick typo fix. Heroku was spelt wrong.

### CODE REVIEW

**Comment by amark** [comment]
@eschapp you rock! Thanks. Merging.

What are you working on?

**Comment by eschapp** [comment]
Playing with 0.5 and Now.sh for the time being. Then who knows?

**Comment by amark** [comment]
@eschapp nice, need any help with anything?

**Comment by eschapp** [comment]
Nope not yet, just was inspired to try it out from one of the podcasts you were on recently. Thanks!

**Pull request merged**
