### PR TITLE
Remove text shadow from website

### PR DESCRIPTION
**Pull request by jmeas**
the text shadow makes the text look like it's being rendered as a low quality JPG or somethin'. it's substantially more readable w.o. the shadow imo.

### CODE REVIEW

**Comment by kevinsimper** [comment]
I was also thinking about making a pull request about this, hehe.

**Comment by metasean** [comment]
We're currently reorganizing our repo to pull the website out of the main repo and consolidate portions of the website.  We'll incorporate this at some point in the near future.

**Comment by kevinsimper** [comment]
@metasean How can new contributors help?

**Comment by metasean** [comment]
@kevinsimper - Thank you for the pull request and inquiring about how you can contribute!  The official website repo is now https://github.com/gundb/gundb.github.io, so if you want to make the request over there, it will make it easier to pull in.  :smile: 

I should be adding an examples page (albeit, it will be a bit sparse) before COB tomorrow, and we should be adding a FAQ page in the next week or so.  Other than that @amark knows where all the bits and pieces are and how he wants to get them reorganized, so there's not a lot for us to do on the code side.  

Do you have any other suggestions or requests for the website?

---

Known website (https://github.com/gundb/gundb.github.io) updates:
 - [ ] incorporate @kevinsimper 's drop shadow pull request
 - [ ] @MetaSean - add examples page
 - [ ] add FAQ page

**Comment by amark** [comment]
@jmeas @kevinsimper phew! sorry we've just been swamped. Definitely looking for help. Hey! I was just in Copenhagen the other week. Back in the USA now but will be in Germany for Ditributed Matters conference next week, and London in October. By chance will you be around any of those places then?

Yeah, I'm trying to move everything into the https://github.com/gundb/gundb.github.io repo for the website so that way the actual code repo isn't bogged down with the weight of images and stuff (I then want to purge a lot of the stuff from the main repo). But I also need to get http://gun.js.org/ to point to the organization page instead, and I've been bouncing between so many things it is taking longer than what I wanted. Thanks for getting involved! What are you guys building/need help with?

**Comment by kevinsimper** [comment]
@amark Nice. Germany was not in my plans at the moment right now, but it looks cool!

I am just interested in gundb because it is open source and easy to get started with, and that is what you want if you start a new project or a quick hack project. I like firebase, but they have not made any effort in providing something you can use in development and in unit/integration test.
I am currently building a project that will help people deploy docker containers very easily called www.blackbeard.io, so I am all in the notion of providing quick and fast wins for developers.

**Comment by jmeas** [comment]
> phew! sorry we've just been swamped

Hey, no problem. I know how that is.

> By chance will you be around any of those places then?

I won't be, I'm afraid!

> Yeah, I'm trying to move everything...

Makes sense.

> What are you guys building/need help with?

I was just checkin' out the project, actually. I kept seeing it mentioned all over the place, so I had to come take a look.

**Comment by amark** [comment]
We finally got the website split out. Is there anyway you could move this to https://github.com/gundb/gundb.github.io ? Thanks. I'm going to close this for now because it no longer applies to this repo and we're going to be deleting the gh-pages branch and all the website related assets. Thanks!

**Pull request closed without merging**
