### PR TITLE
make change to lib/unset.js

### PR DESCRIPTION
**Pull request by resession**
the .unset() method is not working, i made some changes to my local package of gundb and it seems to be doing something, doesn't give errors, and nulls the data. currently it is the following:
`const rel_ = Gun.val.link._;  // '#'`
`const node_ = Gun.node._;  // '_'`

guessing the Gun.val.link._ was from an old version and it might be breaking now. so i changed it to the following:

`const rel_ = '#';  // '#'`
`const node_ = '_';  // '_'`

what do you think?

### CODE REVIEW

**Comment by amark** [comment]
@resession thanks!

I was planning on deprecating/deleting `unset`, do you disagree?

Yes, those seem like the correct changes.

**Comment by resession** [comment]
i am currently using unset. the reason actually came from a stackoverflow post i saw from a conversation you had with a person. i can't find the link right now, i searched for it. but the summary is that to delete some data from an unordered list, unset should be used. maybe i am mistaken about what i read, i can't fully recall. maybe you said .set should be used to add data to an unordered list and i am getting it mixed up with deleting with unset.

the main thing is, does it serve a purpose and does it do something that another method can not do? because if so, then keep it(also would help me so i don't have to make changes to gun-fetch and agregor ebrowser doesn't have to update). but if it truly is just another version of .put(null), then you can depracate it/delete it. all up to you.

**Comment by resession** [comment]
since the changes fixes the issue, you can merge this. and then if you want to deprecate or delete the unset module then you can still do that if you are deciding on it.

**Comment by amark** [comment]
oops sorry I got busy, I need to try this again.

@sammosna reminded me of this, tho he says he tried it and still not working? (The failing unit test is probably my fault, not @resession ,sometimes the filesystem doesn't clean up after itself on the CI runners which causes it to falsely fail)

**Comment by amark** [comment]
Hmm, it keeps timing out. But it looks like things should be fine. If you run `mocha` locally does it pass?

**Comment by amark** [comment]
Ok it went this time. Pulling! Thanks! :) !!!!! Sorry I'm so slow.

**Pull request merged**
