### PR TITLE
Dynamic dependency in react-native/expo

### PR DESCRIPTION
**Pull request by aethiop**

### CODE REVIEW

**Comment by amark** [comment]
@aethiop this is great progress. Unfortunately it causes browser to break, tho I think it gives me a new hint on how to fix, let's schedule another call and try it out. Thanks so much for helping with this!

**Comment by sirpy** [comment]
I dont see why the require for external packages should use "USE" it should
use directly require just like the fix I introduced in
GoodDollar/gun sea.js repo.
It works perfectly fine on native and web, please copy the fix from there

**Comment by aethiop** [comment]
@amark Yes I'm aware...And sure lets schedule a meeting and go from there. And as @sirpy said external packages should just use require, that seems to fix the problem.

**Comment by amark** [comment]
sigh did I never merge your edit @sirpy ? I know I'm bad and lagging behind. (oh, maybe it conflicted with the rewrite, but now that's done, should be easy now) Can you link or re-PR it?

Also, gmail is hiding my GitHub issues/pulls notifications, and I can't find how to reset it, grr.

**Comment by amark** [comment]
@aethiop will you close this since your other one is correct?

**Pull request closed without merging**
