### PR TITLE
[SEA] Migrate from `node-webcrypto-ossl` to `@peculiar/webcrypto`

### PR DESCRIPTION
**Pull request by mboperator**
## Changes
- Removed `node-webcrypto-ossl` optional dependency
- Added `@peculiar/webcrypto`
- Naively patched missing `atob` and `btoa` functions to get tests passing

## Test Suite
Screen Shot 2019-09-14 at 1 04 18 PM

## Notes
- I got a few spec failures due to `atob` and `btoa` missing outside of the browser environment. 
I quickly patched them using this [gist](https://gist.github.com/jmshal/b14199f7402c8f3a4568733d8bed0f25). Let me know if there's another pattern you'd like for me to follow for polyfilling these functions.
- The test suite fails in Node.js:8 with `TypeError: crypto__default.generateKeyPairSync is not a function`. This function -- introduced by `webcrypto` -- was added to `Node@10.12.0`

### CODE REVIEW

**Comment by amark** [comment]
@mboperator such an exemplar of Open Source!! You show up out of nowhere and boom have stuff working (I'm fine with dropping Node 8 support in favor/exchange of not needing OSSL).

I'm super pumped about this, I'll get it merged/published on Monday (with family today/tomorrow).

WELCOME TO THE COMMUNITY, BTW!!!! :D :D :D Would love to hear about your app and transition from Firebase (possibly ???even a blog or case study???), jump into the [chatroom](https://gitter.im/amark/gun)?!

**Comment by mboperator** [comment]
Haha you give me too much credit. I'm glad I can be of help to the cause.

I've just joined the chatroom and I'd be happy to chat about the transition to Firebase (feel free to DM me). 

Enjoy the rest of your weekend ✌🏽

**Comment by amark** [comment]
@mboperator I don't understand, on my machine the tests aren't passing, yet on Travis they are. :( I'm getting errors like:

```
{ Error: error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding
    at Sign.sign (internal/crypto/sig.js:80:26)
    at Function.sign (/Users/mark/node_modules/@peculiar/webcrypto/build/webcrypto.js:1580:34)
    at EcdsaProvider.onSign (/Users/mark/node_modules/@peculiar/webcrypto/build/webcrypto.js:1742:25)
    at EcdsaProvider.sign (/Users/mark/node_modules/@peculiar/webcrypto/node_modules/webcrypto-core/build/webcrypto-core.js:161:28)
    at SubtleCrypto.sign (/Users/mark/node_modules/@peculiar/webcrypto/node_modules/webcrypto-core/build/webcrypto-core.js:787:39)
    at sig.importKey.then (/Users/mark/Dropbox/Public/gun/gun/sea.js:405:49)
  opensslErrorStack:
   [ 'error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib',
     'error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error',
     'error:100D508E:elliptic curve routines:eckey_priv_decode:decode error',
     'error:10092010:elliptic curve routines:d2i_ECPrivateKey:EC lib' ] }
...
```

I don't have `openssl` anymore, so how can it still be sending error stacks?

Hmm, maybe I'll try installing/cloning in a fresh repo.

**Comment by amark** [comment]
going from node `10.16.0` to `10.16.3` didn't fix anything either, gonna try fresh repo now.

**Comment by amark** [comment]
odd, it works in a fresh repo. Maybe this is why my previous attempt didn't work, my main working directory somehow has ghost modules in it?

**Comment by amark** [comment]
@mboperator WAAAHOOO!!!! Finally got this published, there was some weird weird stuff happening on my machine, but its all working now.

NO MORE PYTHON/OSSL!!! YAAAAY!!!!!!!!!!!!!!!!!!!!!!!!!!! PARTY PARTY PARTY!!! 🎉

**Comment by mboperator** [comment]
That is incredibly odd. Are you running system `node` or do you manage it with `nvm`?

Either way STOKED that you got it working and that it's now merged.
This is my first high profile open source contribution and I'm glad it's for this project 😄

**Comment by sirpy** [comment]
I get this new error
 ```
TypeError: keyData: Is not ArrayBufferView or ArrayBuffer
        at Pbkdf2Provider.checkKeyData (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/webcrypto-core/build/webcrypto-core.js:310:19)
        at Pbkdf2Provider.checkImportKey (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/webcrypto-core/build/webcrypto-core.js:242:14)
        at Pbkdf2Provider.checkImportKey (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/webcrypto-core/build/webcrypto-core.js:687:15)
        at Pbkdf2Provider.importKey (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/webcrypto-core/build/webcrypto-core.js:237:29)
        at SubtleCrypto.importKey (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/webcrypto-core/build/webcrypto-core.js:850:29)
        at Object.SEA.work.SEA.work [as work] (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:277:50)
        at Object.act.c (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:846:13)
        at act.e (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:855:24)
        at Object.SEA.decrypt.SEA.decrypt [as decrypt] (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:582:15)
        at act.d (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:849:13)
        at Object.SEA.work.SEA.work [as work] (/Users/hadar/workspace/GoodDollar/GoodBootstrap/packages/server/node_modules/gun/sea.js:292:15)
```

**Comment by ThomasPerche** [comment]
Guys could you explain how to fix this error with btoa :

`(node:15296) UnhandledPromiseRejectionWarning: ReferenceError: btoa is not defined`

Thanks for your work !! Glad to be able to drop python & ossl

**Comment by sirpy** [comment]
@ThomasPerche what platform are you on?
basically you need to define your own btoa in global scope, you can require existing npm packages

**Pull request merged**
