### PR TITLE
👋🏻 Improve CI.

### PR DESCRIPTION
**Pull request by noctisatrae**
This new Github Action will allow the community to build & push a docker image every time a change is merged in the master branch. I know there's already a `release-docker.yml` in the workflows but my solution uses the Github Action made by Docker which make the file prettier because it doesn't use commands.

It's simpler to use and we can always refactor later.

### CODE REVIEW

**Comment by noctisatrae** [comment]
Also, why are we using an old version of node.js ?

**Comment by amark** [comment]
@tcurdt you've been heading this up for a while now, can you approve or ask to modify or explain why not, this PR? Thanks @noctisatrae :)

**Comment by tcurdt** [comment]
Sure thing.

Due to the stupidity of github actions (flawed workflow dependency management) it's easier to use just one workflow. Hence I changed that in the last PR.

I personally have no issues with using the docker actions to do the build as such, but I don't see that much of a benefit either. In fact I find it easier to unterstand what's gong on without them - without having to deal with another dependency. They become interesting mostly when we want to provide more architectures (arm?). IIUC this would need QEMU as well though.

If we would to switch the docker part over (see the current `ci.yml`) - which would be totally possible, we need to make sure all labels and args are set correctly (to match the Dockerfile). Which I don't think is the case like this, and certainly not easy to see.

Also I would recommend not to depend on an exact commit of the version like that, as it will prevent taking advantage of further bug fixes and improvements. I would suggest to depend on a major or minor version match.

**Comment by noctisatrae** [comment]
@tcurdt Do you want my Discord to work in team ? 
It'd be awesome to work on the CI with you!

**Comment by tcurdt** [comment]
@noctisatrae Sure! Feel free to get in touch.
It's `tcurdt` over there as well. I can't do tonight though.
I am in UTC+2.

**Comment by tcurdt** [comment]
We had a quick call and agreed we won't do this now. And if we were to switch to the docker action later we would change this in the `ci.yml`. So this PR can be closed. But thanks @noctisatrae !

**Pull request closed without merging**
