### PR TITLE
New landing page

### PR DESCRIPTION
**Pull request by mmalmi**
Preview at https://gun-iris.herokuapp.com/

### CODE REVIEW

**Comment by amark** [comment]
Yaycakes!!!

Yes, let's do this. Tho it'll only be temporary (which seems to last years lol) until I get the game landing page out, or may get random various tweaks.

Few things first, like we discussed on call: Move images out to iris, move iris into a devDep (for weird reasons that relate to quirky npm behavior) for now.

**Comment by mmalmi** [comment]
Done! As Iris is now a devDependency, it will be only served when you clone the repo and `npm install` or set `NODE_ENV=development` on Heroku.

**Comment by mmalmi** [comment]
I might recommend "Squash and merge" for a cleaner commit log (dropdown from the "Merge pull request" button).

**Comment by amark** [comment]
@mmalmi 👏 👏 👏 👏  yaaay!!

Do me a favor and lookup the heroku 1-click-deploy button template as maybe we can set default envs?

**Pull request merged**
