### PR TITLE
package.json: adopt a common format

### PR DESCRIPTION
**Pull request by Xe**
Some of my vim plugins and zsh tools were choking at the inconsistency.

### CODE REVIEW

**Comment by amark** [comment]
why does Travis say this failed? Nothing seems like it changed other than formatting.

**Comment by Xe** [comment]
It looks like a random failure to me.

**Comment by amark** [comment]
Hmm, this seems like it is NOT your problem, but mine.

v0.6.21 of Node is consistently failing on one of the tests.

Pulling.

**Comment by amark** [comment]
manually pulled, shouldn't github be intelligent enough to know that this is now pulled? Anyways, closing.

**Comment by alexlafroscia** [comment]
Just curious, why are you using such an old version of Node?

**Comment by amark** [comment]
Hey Alex! I was just thinking about you a few minutes ago. :) How are things going, school calming down? I got "groups" (finite sets/lists/collections) working finally, I had some nasty bugs I needed to fix.

I strive for maximal compatibility with most JS environments, since often the runtime is locked down by a vendor (aka schools running IE6 etc.) and not the choice of the user or developer.

However, I realized that doesn't really apply for NodeJS since you are the vendor, so I dropped Node v0.6 support. However, I still some day want to fix it, because the fact that it is consistently failing there suggests that there might be some more devious problem in my code.

**Pull request closed without merging**
