### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by amark** [comment]
Just saw this! (Sorry... github doesn't send me email notifications anymore even tho I have them turned on) In a code session with someone right now but I'll try to remember to look & pull. THANK YOU THANK YOU THANK YOU, very much appreciated. (DM me if I don't pull it soon, to remind, I'm so scattered brain)

**Comment by rex4539** [comment]
@amark Just a reminder :)

**Comment by amark** [comment]
@rex4539 how did you do this? You've covered thousands of lines of code with tiniest of detail that wouldn't seem humanly possible, yet at the same time, it switches between correcting spelling in both comments, tests, docs, and (rarely) code - which an AI would get caught up on a billion other false positives (abbreviations, etc.)

sorry I forgot! One of the big problems is GitHub does not send me email notifications anymore (tho I didn't turn them off). I'm very grateful for this. THank you :) :) :) :)

**Comment by rex4539** [comment]
https://github.com/codespell-project/codespell

**Pull request merged**
