### PR TITLE
updated the tutorial link on the readme page #UTAHJS commit

### PR DESCRIPTION
**Pull request by djmrr**
noticed that the link for the tutorial was taking you to a kinda dead place that just gave you a redirect.
so I just changed the link to the one that it redirects to.

### CODE REVIEW

**Comment by PsychoLlama** [comment]
Hey @djmrr, great catch! Thanks for the pull request!

**Comment by amark** [comment]
thanks @djmrr ! Could @metasean or @PsychoLlama also make sure this makes it to gundb.io website repository? I think the live website is on that one, not this one anymore.

**Comment by PsychoLlama** [comment]
Hmmm, good point. @amark I've tried merging the two locally, and it seems there's quite a bit that's different between the two repos, leaving a few things broken (namely the tutorial)... I'm assuming everything is in the web/ directory. Should one of us submit a duplicate pull request to the gundb.io repo?

**Comment by amark** [comment]
oh no! not the tutorial :( . yeah dup pull request please. and on the gundb.io repo everything is in root level not web/ like it is on this one. thanks!

**Comment by metasean** [comment]
I went ahead and did a pull of the posted master branch, removed the web directory, and pushed back up so that this confusion is drastically reduced.  The [web directory](https://github.com/amark/gun/tree/af30651dddd241c54069fcf40579027449d78c41/web) is still available via the [previous commit](https://github.com/amark/gun/tree/af30651dddd241c54069fcf40579027449d78c41).

**Comment by amark** [comment]
Good idea.

**Pull request merged**
