### PR TITLE
Check for boolean false to disable file.js, https://github.com/amark/…

### PR DESCRIPTION
**Pull request by wehriam**
Cannot disable the default file.js module when using another storage adapter in Node.js.

## Description

Updated `file.js` to test for a boolean false and return.

```js
if(opt.file === false) {
  return;
}
```

## Motivation and Context

Resolves https://github.com/amark/gun/issues/401

## How Has This Been Tested?

Project tests pass. Also tested locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by wehriam** [comment]
Running `yarn install` modified a number of files not included in this commit. Should they be?

```sh
saucer:gun admin$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
$ npm run unbuild

> gun@0.8.3 unbuild /Users/johnwehr/Projects/bunch/gun
> node lib/unbuild.js && uglifyjs gun.js -o gun.min.js -c -m

Done in 1.67s.
saucer:gun johnwehr$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   gun.min.js
	modified:   src/adapters/localStorage.js
	modified:   src/dup.js
	modified:   src/on.js
	modified:   src/onto.js
	modified:   src/put.js
	modified:   src/root.js
```

**Comment by wehriam** [comment]
I also added issue and pull templates: https://github.com/wehriam/gun/tree/master/.github

I've found these to be very helpful in terms of community engagement, but would be happy to remove them if they're superfluous. 

I also noticed this message but could not find any mention of this sponsorship elsewhere. It might be a good idea to put a link to information on sponsorship in the issue template.

`;"Please do not remove these messages unless you are paying for a monthly sponsorship, thanks!";` - https://github.com/amark/gun/blob/master/src/root.js#L198-L200

**Comment by amark** [comment]
Yes, I'd like to add templates... that would be nice (although I hate that all these things... docker/github/mocha all require some root level config file or special folder name. Makes project's repos look ugly! :( Oh well, the templates will be worth it.)

Yes, it is intentional that those `src/` files get generated. Although it was accidental that I didn't "generate" them myself from the previous commit (sometimes I forget, even though it is quasi-automated). Why do those files get generated? We do a futuristic "reverse build" system that makes us backwards compatible with things like webpack, but keeps our hands clean from any holy wars.

I purposefully didn't include the link because I do NOT want it to be easy for people to pay. I'm specifically targeting large corporations / development teams with a comment like that. Such that they'd need to personally contact us (so we know they are using gun). I know this doesn't make sense :P.

Given our discussion in https://github.com/amark/gun/issues/401 , I'm hoping I explained how to exclude `file.js`? If I haven't, I'll provide some more examples - just let me know! Else wise, I'd love to keep this PR and pull it, just minus the actual `opt.file === false` change :P but then we can get the GitHub templates! What do you think?

**Comment by amark** [comment]
Haven't heard back from you in a while, so I'm gonna reference:

https://github.com/amark/gun/pull/424

And then close. Please re-open if you have further thoughts AND/OR modify the PR to just have the templates which I'd go ahead and pull by themselves.

Thanks! Let me know how/if I can help with anything.

**Pull request closed without merging**
