### PR TITLE
Move react example to create-react-app and try to get it syncing

### PR DESCRIPTION
**Pull request by brysgo**
Still haven't gotten it syncing, but it is pretty close and now it is a more conventional `react-scripts` app created with the popular `create-react-app` generator.

### CODE REVIEW

**Comment by amark** [comment]
Thanks! The server still doesn't seem to sync :(, I'm not sure why it is having problems when the regular apps work just fine.

Several examples @zwhitchcox wrote seem to be being deleted, is there any possible way we could add-to them, rather than overwriting/replacing? Maybe we should do a `./examples/create-react-app` folder instead?

**Comment by amark** [comment]
Really appreciate helping out though, makes you a role model to the community on how OSS should work. :) :) :)

**Comment by brysgo** [comment]
Thanks @amark, you're awesome! The json example was syncing for me, but the others weren't. You have to run both `npm start` and `npm run server`. Then make sure you use the version on Port 8081. Since it will have the gun server.

**Comment by amark** [comment]
thaaaanks!

**Pull request merged**
