### PR TITLE
update package.json

### PR DESCRIPTION
**Pull request by zwhitchcox**
export the `unminified` file, which stops people from having to `import 'gun/gun'`.

When people `import 'gun/gun'`, this is what they are doing anyway. Since gun compatible with previous version of ES, there's no harm in exporting the unminified, unaltered file. Users of code bundlers like webpack and rollup will be minifying their code anyway.

### CODE REVIEW

**Comment by zwhitchcox** [comment]
Need

**Comment by amark** [comment]
Oh, why did you close this? Wasn't I suppose to pull?

**Comment by zwhitchcox** [comment]
Reopening, because it makes it harder to debug with the `min` version

**Comment by amark** [comment]
Sure thing, debugging is pretty important! Pulling.

**Comment by zwhitchcox** [comment]
Sweet!

**Pull request merged**
