### PR TITLE
SEA concurrent possible fix

### PR DESCRIPTION
**Pull request by sirpy**
https://github.com/amark/gun/issues/795

confirmed as fixing issue

@amark @mhelander  
are there any unit tests for SEA to make sure it breaks nothing?

### CODE REVIEW

**Comment by sirpy** [comment]
@amark how do I locally rebuild the sea.js file?
I see that it is used for tests and not the src files

**Comment by sirpy** [comment]
@amark doesnt  pass build on node8 have no idea why

**Comment by sirpy** [comment]
@amark ok seems everything is ok. can we merge? this also include the revert of stats.js you still didnt commit to master

**Comment by mhelander** [comment]
@sirpy I see your correction to `secret.js` is valid. Definitely we don't want to mutate in this `Object.assign` call...

**Comment by amark** [comment]
if @mhelander thinks it looks good, then so do I!!!

@sirpy nice fix! @sirpy is a hero!! 👏 👏 👏 gonna be bragging about you on the chat tomorrow when I wake up. ;)

Yes, no worries about the build, that is easy for me to do, the most important piece is figuring the fix which you did. Thank you!!!!!!!!!!!!!!!!!!!

**Pull request merged**
