### PR TITLE
Fix user.create() callback not firing and user.create(pair)

### PR DESCRIPTION
**Pull request by mimiza**
- Switched back to using spread operator (as Mark noted), using (...args) instead of "arguments"
- Wrap JSON.parse(sS.pair) in a try{}catch{}

### CODE REVIEW

**Comment by mimiza** [comment]
@amark 
NEWEST COMMITS:
BEFORE:
- user.create(pair) --> ~@[object Object]
- (noop == cb) --> callback in user.create() will never fire (no matter cb or !cb) because functions can't be compared like this (noop == cb). For example:
```
const a = b = function(){};
a == b // FALSE
```

AFTER:
- user.create(pair) --> ~@pair.pub
- callback is fired

**Comment by danlugo92** [comment]
`npm test`

relevant output:
```
SEA
      Utility
        ✓ quickstart (300ms)
Signature did not match.
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.from (/home/daniel/workspace/mimiza-gun/sea.js:97:17)
    at Object.SEA.opt.fall_verify (/home/daniel/workspace/mimiza-gun/sea.js:487:27)
    at async Object.SEA.verify (/home/daniel/workspace/mimiza-gun/sea.js:448:18)
Could not decrypt
Could not decrypt
        ✓ quickwrong
        ✓ types
        ✓ atypes
Warning: reusing same fs store and options as 1st.
Could not decrypt
migrate core account from UTF8 & shuffle
        ✓ legacy (1007ms)
Warning: reusing same fs store and options as 1st.
migrate core account from UTF8 & shuffle
        ✓ legacy [] (731ms)
        ✓ JSON escape
Signature did not match.
Signature did not match.
        ✓ double sign

//.........

132 passing (27s)
  10 pending


```
Process quits yet "10 pending"?

Then ran again...
```
 77 passing (11s)
  3 pending
  4 failing

  1) Gun
       RAD
         RAD + GUN
           write contacts:
     Uncaught Error: expected [Error: ENOENT: no such file or directory, rename 'radatatest-%1C-py9.tmp' -> 'radatatest/%1C'] to be falsy
      at Assertion.assert (test/expect.js:96:13)
      at Assertion.ok (test/expect.js:115:10)
      at Function.ok (test/expect.js:499:17)
      at Object.ack (test/rad/rad.js:308:43)
      at Object.<anonymous> (gun.js:1595:9)
      at Object.onto [as on] (gun.js:205:41)
      at Object.ask (gun.js:628:16)
      at Object.universe [as next] (gun.js:725:12)
      at Object.onto [as on] (gun.js:205:41)
      at DBG.r (lib/store.js:24:27)
      at s.ack (lib/radisk.js:112:13)
      at f.both (lib/radisk.js:203:12)
      at f.both (lib/radisk.js:202:12)
      at f.both (lib/radisk.js:203:12)
      at f.both (lib/radisk.js:203:12)
      at f.both (lib/radisk.js:203:12)
      at f.both (lib/radisk.js:203:12)
      at safe (lib/radisk.js:162:7)
      at /home/daniel/workspace/mimiza-gun/lib/rfs.js:60:5
      at FSReqCallback.oncomplete (fs.js:155:23)

  2) Gun
       SEA
         User
           User's nodes must be signed when on user scope!:
     Uncaught Error: expected 'Error: No ACK yet.' to be falsy
      at Assertion.assert (test/expect.js:96:13)
      at Assertion.ok (test/expect.js:115:10)
      at Function.ok (test/expect.js:499:17)
      at Object.ack (test/rad/rad.js:308:43)
      at Object.<anonymous> (gun.js:1595:9)
      at Timeout._onTimeout (gun.js:636:8)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  3) Gun
       SEA
         User
           predictable souls
             user's:
     Uncaught Error: expected 'Error: No ACK yet.' to be falsy
      at Assertion.assert (test/expect.js:96:13)
      at Assertion.ok (test/expect.js:115:10)
      at Function.ok (test/expect.js:499:17)
      at Object.ack (test/rad/rad.js:308:43)
      at Object.<anonymous> (gun.js:1595:9)
      at Timeout._onTimeout (gun.js:636:8)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  4) Gun
       Utility
         flow
           intermittent interruption:
     Uncaught TypeError: Cannot read property 'isPending' of undefined
      at processImmediate (internal/timers.js:456:21)



npm ERR! Test failed.  See above for more details.
daniel@daniel-laptop:~/workspace/mimiza-gun$ 


```


Then I ran once more and got similar if not equal results to the first run. (!!)
Ran once more got similar results to 2nd run.
Ran once more got similar results to 1st run.

There's a pattern in there.

Seems to alternate between 77 tests passing and 132 on each cycle.

**Comment by mimiza** [comment]
@danlugo92 Thank you for the test. I tried to dive the sea and found that the following error is from 'quickwrong' which is designed to be error (which means it's fine):
```
Signature did not match.
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.from (/home/daniel/workspace/mimiza-gun/sea.js:97:17)
    at Object.SEA.opt.fall_verify (/home/daniel/workspace/mimiza-gun/sea.js:487:27)
    at async Object.SEA.verify (/home/daniel/workspace/mimiza-gun/sea.js:448:18)
Could not decrypt
Could not decrypt
```
Everything else I'm not really sure. I don't have much of knowledge about gun/sea to dive deeper and talk further. Maybe wait for @amark to take a look. We should make a call about this :D

**Comment by sirpy** [comment]
@danlugo92 pending tests usually means tests that have been disabled with an X prefix.
"xit", "xtest"

regarding test failures in second run, maybe the tests create some data on disk that then conflicts. try to delete all "radata" and stuff files

**Comment by amark** [comment]
@mimiza 👏 👏 👏 👏 👏 👏 ⚡ ⚡ ⚡ ⚡ ⚡ 🔥 🔥 🔥 🔥

@sirpy @jabis @Dletta wasn't there something else that needed to get merged & published as well?

**Comment by mimiza** [comment]
Yaay finally. Thank you

**Comment by sirpy** [comment]
@amark there's the PR with  the changes required for expo

**Pull request merged**
