### PR TITLE
Updated readability of chat example and minor html updates

### PR DESCRIPTION
**Pull request by TheHollidayInn**
- Moved styles to head
- Moved styles from html to css
- Updated JS formatting

### CODE REVIEW

**Comment by amark** [comment]
@TheHollidayInn thanks! Will pull, but one dumb question (since there aren't automated tests for the example)

 - You can confirm this example still worked correctly / synced after you updated? (Aka, you tested it?)

Thanks! Then I'll pull. :D

**Comment by amark** [comment]
testing locally is fine, pulling! I'm not sure how you'd automatically "test" an app/UI (other than maybe with PANIC?).

You are a super star!!!! Thanks so much for helping. :) :) :)

**Comment by TheHollidayInn** [comment]
Np! I was thinking of adding this for tests: https://devexpress.github.io/testcafe/documentation/getting-started/

**Comment by amark** [comment]
That is a good start, but that would only test if the app is working within the one page, not across devices. For example: Alice clicks "submit", we should verify that Bob sees it on a different tab.

The second part (testing across devices/tabs) can be done with PANIC, the first part, controlling/manipulating the UI, testcafe looks super nice!!!

**Pull request merged**
