### PR TITLE
0.4 websocket migration

### PR DESCRIPTION
**Pull request by d3x0r**
This version uses 'websocket' which allows connecting with 'wss:' instead of just 'ws:'

Adds some protocol options?

Does update to use protocol 'gun' by default.
This will cause issues if server and client mismatch.

I ran into a issue connecting server-server using Peer.js; should be fixed ( will test tomorrow )

### CODE REVIEW

**Comment by amark** [comment]
`ws` allows for connecting via `wss://` also, we shouldn't have to switch libraries no?

**Comment by d3x0r** [comment]
changes from 'ws' npm to 'websocket'  (reflected in package.json update?)

**Comment by amark** [comment]
I am wanting to clarify:

You said that module `ws` does not support using `wss://` secure transport. Right?

I believe this is false, as I've seen module `ws` successfully connect using `wss://` secure transport.

**Comment by d3x0r** [comment]
it doesn't if using a self signed cert.  I tried using the environment variable ...

set NODE_TLS_REJECT_UNAUTHORIZED=0 or
process.env.NODE_TLS_REJECT_UNAUTHORIZED="0"

And that didn't help 'ws' module connect.

**Pull request closed without merging**
