### PR TITLE
fix(types): .set() should allow IGunChainReference

### PR DESCRIPTION
**Pull request by kylebjordahl**
First off, thanks for the great work on Gun! I've been a long time lurker/tinkerer, but I'm finally getting around to a real project with it.

This PR fixes a small typescript bug that I ran into (I think!) -- per the example in the docs for `.set()`, it seems that one should be able to pass either an object with the acceptable key/value types (as is currently already checked for) or an `IGunChainReference<T>` where T meets the same key/value constraints.

```ts
interface Person {
    name: string
    friends: Person[]
}

var gun = Gun<Record<string, Person>>();
var bob = gun.get('bob').put({name: "Bob"});
var dave = gun.get('dave').put({name: "Dave"});

dave.get('friends').set(bob); // <--- These both throw typescript errors for me, because `bob` and `dave`
bob.get('friends').set(dave); // <--- are both IGunChainableReference<Person>, not Person
```
I've added a utility type of `MaybeGunChainReference` which is simply a union like `T | IGunChainReference<T>` and wrapped the entire `data` argument type of `set()` with this utility type

I also simplified the type definition of `data` using the `Record` in place of the index signature type.

## Updates

I also ran into a problem with the definition of `.map()`, if I call map on a non-array property, Gun expects to simply iterate over the keys, however the return type of `.map()` forces the chain to `never` if the mapped property is not an array type, despite it working fine at runtime.

I've added some additional type logic for cases where the mapped property is not an array but is an object. This can likely be improved in the future to filter out any non-conforming keys, etc.

### CODE REVIEW

**Comment by amark** [comment]
@kylebjordahl 🤯 I have no clue what `IGunChainableReference` is, lol, but I am so happy there are TypeScript people figuring it out for me. If anyone wants to clean it up do be cleaner/shorter names??? Please do! Or... maybe it is intentionally long?

Merging... tho now it is complaining it conflicts, can someone fix for me? I'm not smartypescript enough.

**Comment by kylebjordahl** [comment]
I'll look at merge conflicts in the morning (PST) and update you when it's ready, @amark

**Comment by KenEucker** [comment]
I am also trying to work with gun in TypeScript and I would love to see this PR merged in. Any chance of an update on this? @amark ?

**Comment by kylebjordahl** [comment]
@KenEucker - unfortunately I got very distracted from this and haven't had a chance to clean up for merge; I'm glad to hand this off if its useful though

**Comment by KenEucker** [comment]
@kylebjordahl ahhh, I didn't realize that this wasn't clean for merge. I'm still struggling through TypeScript + GunJS so I might have to circle back a bit later.

**Review by haveanicedavid — APPROVED** [review]
~~Any chance we can get this merged? Minor QOL improvement for us TS folks :)~~

EDIT: Somehow missed the conflicts. Whoop - please disregard

**Review by samailamalima — APPROVED** [review]

**Comment by samailamalima** [comment]
close change

**Pull request closed without merging**
