### PR TITLE
Make `data.json` human-readable

### PR DESCRIPTION
**Pull request by PsychoLlama**
Since the file.js module is only for development or getting started, we shouldn't have to minify the data before persisting it. In fact, it may hurt things, since it obfuscates our data structure and makes it harder
to understand what's going on under the hood.

In this commit, I swapped `Gun.text.ify` with JSON's `stringify` and gave it a 2-space formatting option to make the data more readable.

### CODE REVIEW

**Comment by PsychoLlama** [comment]
@amark, any idea what happened to the build? [13 tests are failing](https://travis-ci.org/amark/gun/jobs/131993515) on node v0.6...
None of the behavior changed. Should I try re-running it?

**Comment by amark** [comment]
Yay!!

Oh ugh. Are we sure 2-space formatting option works on Node v0.6?

Also, the first one that failed is just a perf check, it could be possible that pretty-ify takes slightly longer and thus slows things down slightly, and thus causing the perf check to fail (which then causes a cascade? It shouldn't). Yeah, let's try a rerun and if that doesn't work potentially upping the timeout since it is now arbitrary with the new real perf version coming out.

**Comment by PsychoLlama** [comment]
Yep, re-running the build fixed it. Seems like our tests have a race condition...

**Comment by amark** [comment]
Woohoo it is passing!

(performance tests are by definition a race condition :P)

**Pull request merged**
