### PR TITLE
🎉 Introducing a new feature !

### PR DESCRIPTION
**Pull request by noctisatrae**
You can now create a .hubignore file to prevent hub to upload some files on the DB ! Also, I'm going to write the documentation just after I open this PR.

### CODE REVIEW

**Comment by noctisatrae** [comment]
There is one problem though : it doesn't support folders in `.hubignore` & `./` or `/`. e.g : 
```
./folder/whatever.txt
```

One solution would be to do that : 
```js
hubignore.replace(/^../gm, '/')

// It'd allow us to merge the two parts of the path together.
```

**Comment by noctisatrae** [comment]
I've added simple tests in the test folder + I fixed an issue : when hub saved a file into Gun, its path had two "/" if the user gave something like that : "/home/noctisatrae/gun/tests/hub". Now, it won't !

**Review by noctisatrae — COMMENTED** [review]
I tested eveything on my computer and all is working ! The `.hubignore` file do his work and after the merge of this PR, we'll move on the protection of the data!

**Comment by alterx** [comment]
+1 for protection of the data!

Great work with all this @noctisatrae

**Comment by noctisatrae** [comment]
Thanks ! I hope my PR will soon be reviewed my @amark !

**Comment by noctisatrae** [comment]
Yaaaay !!!

**Pull request merged**
